In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from datetime import datetime as dt
import traceback
import numpy as np

from config import filename

import warnings
warnings.filterwarnings("ignore")

# Filter subtitle

In [22]:
subtitles_to_remove = ["Arcade Archives",
                       "Warhammer",
                       "FINAL FANTASY",
                       "Disney",
                       "LEGO®",
                       "Funko Fusion",
                       "Outbreak:",
                       "Nickelodeon",
                       "MLB®",
                       "Moonshine",
                       "Supermarket Manager",
                       "Call of Duty®",
                       "Cazzarion",
                       "ACA NEOGEO",
                       "Argonauts",
                       "Assassin's Creed",
                       "The Walking Dead",
                       "Grim Legends",
                       "Russia",
                       "Lost Grimoires",
                       "DRAGON BAL",
                       "Watch Dogs",
                       "Skull and Bones",
                       "Overcooked",
                       "The Legend of Heroes",
                       "Sonic",
                       "SpongeBob",
                       "Star Wars",
                       "Star Trek",
                       "Crash Bandicoot",
                       "MotoGP™",
                       "Resident Evil",
                       "Vampire",
                       "HOT WHEELS",
                       "JIGSAW",
                       "One Piece",
                       "Tom Clancy",
                       
                      ]

In [23]:
title_substring = subtitles_to_remove[-1]

df = pd.read_csv(filename)

for subtitle in subtitles_to_remove:
    df.loc[df[df['title'].str.contains(title_substring)].index, 'status'] = -1

df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)
df.to_csv(filename, index=False)

In [24]:
title_substring = subtitles_to_remove[-1]
df[df['title'].str.contains(title_substring)]

,title,platform,psd_URL,icon_URL,price,status
13497,Tom Clancy's Ghost Recon® Breakpoint,PS4,https://psdeals.net/ua-store/game/1901939/tom-...,https://store.playstation.com/store/api/chihir...,"1,497.00₴",-1
13498,Tom Clancy's Ghost Recon® Breakpoint Deluxe Ed...,PS4,https://psdeals.net/ua-store/game/2272949/tom-...,https://store.playstation.com/store/api/chihir...,"2,228.00₴",-1
13499,Tom Clancy's Ghost Recon® Breakpoint Gold Edition,PS4,https://psdeals.net/ua-store/game/1901938/tom-...,https://store.playstation.com/store/api/chihir...,"2,496.00₴",-1
13500,Tom Clancy's Ghost Recon® Breakpoint Ultimate ...,PS4,https://psdeals.net/ua-store/game/2272950/tom-...,https://store.playstation.com/store/api/chihir...,"3,145.00₴",-1
13501,Tom Clancy's Rainbow Six Siege PS5 Upgrade Edi...,PS5 / PS4,https://psdeals.net/ua-store/game/2357571/tom-...,https://store.playstation.com/store/api/chihir...,649.00₴,-1
13502,"Tom Clancy's Rainbow Six® Эвакуация: набор ""Ед...",PS4,https://psdeals.net/ua-store/game/2326951/tom-...,https://store.playstation.com/store/api/chihir...,"2,279.00₴",-1
13503,"Tom Clancy's Rainbow Six® Эвакуация: набор ""Ед...",PS5 / PS4,https://psdeals.net/ua-store/game/2326942/tom-...,https://store.playstation.com/store/api/chihir...,"2,279.00₴",-1
13504,Tom Clancy's The Division 2 - Версія Ultimate ...,PS4,https://psdeals.net/ua-store/game/1996027/tom-...,https://store.playstation.com/store/api/chihir...,"1,699.00₴",-1
13505,Tom Clancy's The Division™ Gold Edition,PS4,https://psdeals.net/ua-store/game/73018/tom-cl...,https://store.playstation.com/store/api/chihir...,"1,199.00₴",-1
13506,Tom Clancy’s Ghost Recon Breakpoint - Standard...,PS4,https://psdeals.net/ua-store/game/1796216/tom-...,https://store.playstation.com/store/api/chihir...,"1,497.00₴",-1
13507,Tom Clancy’s Ghost Recon® Wildlands - Deluxe E...,PS4,https://psdeals.net/ua-store/game/858587/tom-c...,https://store.playstation.com/store/api/chihir...,"1,599.00₴",-1
13508,Tom Clancy’s Ghost Recon® Wildlands - Standard...,PS4,https://psdeals.net/ua-store/game/974975/tom-c...,https://store.playstation.com/store/api/chihir...,973.00₴,-1
13509,Tom Clancy’s Ghost Recon® Wildlands Ultimate E...,PS4,https://psdeals.net/ua-store/game/1607067/tom-...,https://store.playstation.com/store/api/chihir...,"2,599.00₴",-1
13510,Tom Clancy’s Ghost Recon® Wildlands Year 2 Gol...,PS4,https://psdeals.net/ua-store/game/1607068/tom-...,https://store.playstation.com/store/api/chihir...,"1,899.00₴",-1
13511,Tom Clancy’s Rainbow Six® Extraction Deluxe Ed...,PS5 / PS4,https://psdeals.net/ua-store/game/2215402/tom-...,https://store.playstation.com/store/api/chihir...,"1,579.00₴",-1
13512,Tom Clancy’s Rainbow Six® Extraction PS4 and PS5,PS5 / PS4,https://psdeals.net/ua-store/game/2215403/tom-...,https://store.playstation.com/store/api/chihir...,"1,329.00₴",-1
13513,Tom Clancy’s The Division 2 - версія Ultimate ...,PS4,https://psdeals.net/ua-store/game/2966186/tom-...,https://store.playstation.com/store/api/chihir...,"1,999.00₴",-1
13514,Tom Clancy’s The Division 2,PS4,https://psdeals.net/ua-store/game/1753290/tom-...,https://store.playstation.com/store/api/chihir...,859.00₴,-1
13515,Tom Clancy’s The Division 2 - версія Gold Edition,PS4,https://psdeals.net/ua-store/game/2966184/tom-...,https://store.playstation.com/store/api/chihir...,"1,719.00₴",-1
14874,«Tom Clancy's Rainbow Six. Облога»,PS4,https://psdeals.net/ua-store/game/14076/tom-cl...,https://store.playstation.com/store/api/chihir...,709.00₴,-1
14875,"«Tom Clancy’s Rainbow Six. Облога», Operator E...",PS5 / PS4,https://psdeals.net/ua-store/game/2745004/tom-...,https://store.playstation.com/store/api/chihir...,"1,999.00₴",-1
14876,"«Tom Clancy’s Rainbow Six. Облога», Ultimate E...",PS5 / PS4,https://psdeals.net/ua-store/game/2745005/tom-...,https://store.playstation.com/store/api/chihir...,"2,599.00₴",-1
14982,Ексклюзивний випуск «Tom Clancy's Rainbow Six....,PS5 / PS4,https://psdeals.net/ua-store/game/2745003/%D0%...,https://store.playstation.com/store/api/chihir...,859.00₴,-1

# Delete publisher

In [7]:
def get_pub(publisher):
    
    time = dt.now()
    
    page_num = 1
    df_pub = pd.DataFrame(columns=['title', 'platform', "psd_URL", "icon_URL", "price"])

    prev_page = None

    while True:
        try:
            URL = f"https://psdeals.net/ua-store/all-games/{page_num}?publisher={publisher}"
            #URL = f"https://psdeals.net/ua-store/all-games{page_num}?contentType%5B%5D=games&contentType%5B%5D=bundles&feature%5B%5D=vrGames"

            headers = requests.utils.default_headers()
            page = requests.get(URL, headers=headers)

            soup = BeautifulSoup(page.content, "html.parser")

            grid_items = soup.find_all('div', class_='game-collection-item col-md-2 col-sm-4 col-xs-6')

            if grid_items == prev_page:
                break

            for item in grid_items:

                title = item.find('span', class_='game-collection-item-details-title').text
                platform = item.find('span', class_='game-collection-item-top-platform').text
                image = item.find('img', class_='game-collection-item-image lazy').get('data-src')
                psd_link = "https://psdeals.net" + item.find('a', class_='game-collection-item-link').get('href')

                try:
                    price = item.find('span', class_='game-collection-item-price').text
                except:
                    price = np.NaN

                new_row = {"title": title, 
                           "platform": platform,
                           "price": price,
                           "psd_URL": psd_link,
                           "icon_URL": image}


                df_pub = df_pub.append(new_row, ignore_index=True)

            print(f"page {page_num}  time {dt.now() - time}")

            page_num += 1

            prev_page = grid_items

        except Exception as e:
            print(e)
            print(traceback.format_exc())
            break
            
    return df_pub

In [8]:
bad_publishers_list = ["Kanuni+games+oyun+YAZILIM+VE+Pazarlama+Ticaret+limited+Sirketi",
                       "Kimulator%27s+Films+inc.",
                       "MARKT%2BTECHNIK+VERLAG+GMBH",
                       "NOSTRA+GAMES+LTD",
                       "JOINDOTS+GMBH",
                       "SMOBILE+INC",
                       "KODOBUR+YAZILIM+BILISIM+TASARIM+ARG",
                       "ThiGames",
                       "Entalto+Games+SL",
                       "OÜ+Enningture+Game+Temple",
                       "Gametry+sp.+z+o.+o.",
                       "QUBICGAMES+SP.+Z+O.O.",
                       "Klovako+s.+r.+o.",
                       "Benoit+Varasse+trading+as+Pix+Arts",
                       "Game+Achievements+Ltd",
                       "Zakym+s.+r.+o.",
                       "Acyntha",
                       "CLICKTEAM+LLC+USA",
                       "Webnetic+s.+r.+o.",
                       "Scout+Game+Studios+Sociedad+Anonima",
                       "THOMAS+CLAUS+UND+FRANK+MENZEL",
                       "Microids",
                       "EVGENIY+KOLPAKOV",
                       "QUBYTE+INTERACTIVE",
                       "Feardemic",
                       "Aristo+Studio+s.r.o.",
                       "RECOTECHNOLOGY+S.L.",
                       "We+Dig+Games+sp.+z+o.o.",
                       "OCEAN+MEDIA+LLC",
                       "Breakthrough+Gaming+LLC",
                       "Wales+Interactive+Limited",
                       "ONSKULL+DEVELOPMENT",
                       "Xitilon",
                       "Nellyvision+Ltd",
                       "VRCFORGE+STUDIOS+LTD",
                       "Dead+Drop+Studios+LLC",
                       "7+RAVEN+STUDIOS+CO.+LTD.",
                       "Take+IT+Studio%21+Sp.+z+o.o.",
                       "SILESIA+GAMES+SP.+Z+O.O.",
                       "SUPER+POWERUP+GAMES%2C+SOCIEDAD+LIMITADA",
                       "ERDEM+SEN",
                       "Saber+Interactive%2C+Inc",
                       "BIG+WAY+GAMES",
                       "Lightwood+Games",
                       "Revolt+Games+SRL",
                       "Volkov+Konstantin+Sergeevich",
                       "4HIT",
                       "ARTIFEX+MUNDI+SP.+Z+O.O.",
                       "THE+VOICES+GAMES+LTD",
                       "GGMUKS+INC.",
                       "BLITWORKS+SL",
                       "Aksys+Games+Localization+Inc.",
                       "Blue+Brain+Games+s.r.o.",
                       "YASH+FUTURE+TECH+SOLUTIONS+PVT+LTD",
                       "Slitherine",
                       "NUMSKULL+GAMES+LTD",
                       "MIDNIGHT+GAMES+S.R.L",
                       "JACKBOX+GAMES%2C+INC.",
                       "GOGAME+CONSOLE+PUBLISHER+LTD",
                       "GameToTop+Corporation+LTD",
                       "RATALAIKA+GAMES+SL",
                       "ASI+GAMES+TECHNOLOGIES+LTD",
                       "ESDigital+Games+LTD",
                       "Ravenscourt",
                       "COOL+DEVS+S.R.L",
                       "ASTRAGON+ENTERTAINMENT+GMBH",
                       "ARTIFEX+MUNDI+S.A.",
                       "KLABATER",
                       "VICTORY+ROAD",
                       "AEROSOFT+GMBH",
                       "Frozen+District",
                       "Midnight+Works+SRL",
                       "ADVENTURE+GAMES+S.R.L",
                       "4+GLADIATORS",
                       "DEZVOLT+APP+%26+IDEI+SRL",
                       "PARADOX+INTERACTIVE+AB",
                       "QUBICGAMES+S.A.",
                       "SABEC+LIMITED",
                       "APPWILL+COMPANY+LTD",
                       "Gaijin+Distribution+KFT",
                       '"Contrast Games" Limited Liability Partnership'
                      
                      ]

In [9]:
publisher = bad_publishers_list[-1]

df_pub = get_pub(publisher)        

df = pd.read_csv(filename)

df.loc[df[df['title'].isin(df_pub.title)].index, 'status'] = -1
df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)
df.to_csv(filename, index=False)

page 1  time 0:00:00.922548

# Sort

In [13]:
df = pd.read_csv(filename)
df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)
df.to_csv(filename, index=False)

In [4]:
df.head(10)

,title,platform,psd_URL,icon_URL,price,status
0,A Way Out,PS4,https://psdeals.net/ua-store/game/1480053/a-wa...,https://store.playstation.com/store/api/chihir...,"1,049.00₴",1.0
1,ASTRO BOT,PS5,https://psdeals.net/ua-store/game/2787643/astr...,https://store.playstation.com/store/api/chihir...,"1,999.00₴",1.0
2,Akimbot,PS5,https://psdeals.net/ua-store/game/2828034/akimbot,https://store.playstation.com/store/api/chihir...,649.00₴,1.0
3,Alan Wake Remastered,PS5 / PS4,https://psdeals.net/ua-store/game/2263208/alan...,https://store.playstation.com/store/api/chihir...,799.00₴,1.0
4,Atomfall PS4™ & PS5™,PS5 / PS4,https://psdeals.net/ua-store/game/2877835/atom...,https://store.playstation.com/store/api/chihir...,"1,799.00₴",1.0
5,Burnout™ Paradise Remastered,PS4,https://psdeals.net/ua-store/game/1474936/burn...,https://store.playstation.com/store/api/chihir...,649.00₴,1.0
6,Caravan SandWitch,PS5,https://psdeals.net/ua-store/game/2835297/cara...,https://store.playstation.com/store/api/chihir...,819.00₴,1.0
7,Clair Obscur: Expedition 33,PS5,https://psdeals.net/ua-store/game/2912116/clai...,https://store.playstation.com/store/api/chihir...,"1,499.00₴",1.0
8,Ctrl Alt Ego,PS5,https://psdeals.net/ua-store/game/2843851/ctrl...,https://store.playstation.com/store/api/chihir...,819.00₴,1.0
9,Cuphead & The Delicious Last Course,PS4,https://psdeals.net/ua-store/game/2404934/cuph...,https://store.playstation.com/store/api/chihir...,879.00₴,1.0

# Delete duplicates

In [4]:
df = pd.read_csv(filename)
df.drop_duplicates(subset=['title', 'platform', 'psd_URL'], keep=False, inplace=True)
df.to_csv(filename, index=False)

In [5]:
df.head()

,title,platform,psd_URL,icon_URL,price,status
0,Techno Banter: Ultimate Mix,PS5,https://psdeals.net/ua-store/game/2873228/tech...,https://store.playstation.com/store/api/chihir...,649.00₴,0.0
1,"Warhammer 40,000: Darktide",PS5,https://psdeals.net/ua-store/game/2873227/warh...,https://store.playstation.com/store/api/chihir...,759.00₴,0.0
2,"Warhammer 40,000: Darktide - Imperial Edition",PS5,https://psdeals.net/ua-store/game/2873226/warh...,https://store.playstation.com/store/api/chihir...,"1,139.00₴",0.0
3,Techtonica,PS5,https://psdeals.net/ua-store/game/2873225/tech...,https://store.playstation.com/store/api/chihir...,999.00₴,0.0
4,Skydivers Paradise,PS4,https://psdeals.net/ua-store/game/2873224/skyd...,https://store.playstation.com/store/api/chihir...,64.00₴,0.0

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv(filename)