In [4]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from datetime import datetime as dt
import traceback
import numpy as np

from config import filename

import warnings
warnings.filterwarnings("ignore")

# Filter subtitle

In [65]:
subtitles_to_remove = ["Arcade Archives",
                       "Warhammer",
                       
                      ]

In [66]:
title_substring = subtitles_to_remove[-1]

df = pd.read_csv(filename)

for subtitle in subtitles_to_remove:
    df.loc[df[df['title'].str.contains(title_substring)].index, 'status'] = -1

df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)
df.to_csv(filename, index=False)

In [67]:
title_substring = subtitles_to_remove[-1]
df[df['title'].str.contains(title_substring)]

,title,platform,psd_URL,icon_URL,price,status
13990,Arcade Archives 10-Yard Fight,PS4,https://psdeals.net/ua-store/game/1544051/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1
13991,Arcade Archives 64th. STREET,PS4,https://psdeals.net/ua-store/game/2112849/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1
13992,Arcade Archives AERO FIGHTERS,PS4,https://psdeals.net/ua-store/game/2703038/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1
13993,Arcade Archives ARABIAN,PS4,https://psdeals.net/ua-store/game/2097945/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1
13994,Arcade Archives ASSAULT,PS4,https://psdeals.net/ua-store/game/2468863/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1
...,...,...,...,...,...,...
14292,Arcade Archives XX MISSION,PS4,https://psdeals.net/ua-store/game/1991806/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1
14293,Arcade Archives YOUKAI DOUCHUKI,PS4,https://psdeals.net/ua-store/game/2378103/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1
14294,Arcade Archives Yie Ar KUNG-FU,PS4,https://psdeals.net/ua-store/game/1941792/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1
14295,Arcade Archives ZERO TEAM,PS4,https://psdeals.net/ua-store/game/2126868/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1
14296,Arcade Archives ZING ZING ZIP,PS4,https://psdeals.net/ua-store/game/2645648/arca...,https://store.playstation.com/store/api/chihir...,229.00₴,-1

# Delete publisher

In [5]:
def get_pub(publisher):
    
    time = dt.now()
    
    page_num = 1
    df_pub = pd.DataFrame(columns=['title', 'platform', "psd_URL", "icon_URL", "price"])

    prev_page = None

    while True:
        try:
            URL = f"https://psdeals.net/ua-store/all-games/{page_num}?publisher={publisher}"
            #URL = f"https://psdeals.net/ua-store/all-games{page_num}?contentType%5B%5D=games&contentType%5B%5D=bundles&feature%5B%5D=vrGames"

            headers = requests.utils.default_headers()
            page = requests.get(URL, headers=headers)

            soup = BeautifulSoup(page.content, "html.parser")

            grid_items = soup.find_all('div', class_='game-collection-item col-md-2 col-sm-4 col-xs-6')

            if grid_items == prev_page:
                break

            for item in grid_items:

                title = item.find('span', class_='game-collection-item-details-title').text
                platform = item.find('span', class_='game-collection-item-top-platform').text
                image = item.find('img', class_='game-collection-item-image lazy').get('data-src')
                psd_link = "https://psdeals.net" + item.find('a', class_='game-collection-item-link').get('href')

                try:
                    price = item.find('span', class_='game-collection-item-price').text
                except:
                    price = np.NaN

                new_row = {"title": title, 
                           "platform": platform,
                           "price": price,
                           "psd_URL": psd_link,
                           "icon_URL": image}


                df_pub = df_pub.append(new_row, ignore_index=True)

            print(f"page {page_num}  time {dt.now() - time}")

            page_num += 1

            prev_page = grid_items

        except Exception as e:
            print(e)
            print(traceback.format_exc())
            break
            
    return df_pub

In [70]:
bad_publishers_list = ["Kanuni+games+oyun+YAZILIM+VE+Pazarlama+Ticaret+limited+Sirketi",
                       "Kimulator%27s+Films+inc.",
                       "MARKT%2BTECHNIK+VERLAG+GMBH",
                       "NOSTRA+GAMES+LTD",
                       "JOINDOTS+GMBH",
                       "SMOBILE+INC",
                       "KODOBUR+YAZILIM+BILISIM+TASARIM+ARG",
                       "ThiGames",
                       "Entalto+Games+SL",
                       "OÜ+Enningture+Game+Temple",
                       "Gametry+sp.+z+o.+o.",
                       "QUBICGAMES+SP.+Z+O.O.",
                       "Klovako+s.+r.+o.",
                      
                      
                      ]

In [71]:
publisher = bad_publishers_list[-1]

df_pub = get_pub(publisher)        

df = pd.read_csv(filename)

df.loc[df[df['title'].isin(df_pub.title)].index, 'status'] = -1
df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)
df.to_csv(filename, index=False)

page 1  time 0:00:01.041348
page 2  time 0:00:01.970275
page 3  time 0:00:02.862843

# Sort

In [9]:
df = pd.read_csv(filename)
df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)
df.to_csv(filename, index=False)

In [7]:
df.head(10)

,title,platform,psd_URL,icon_URL,price,status
0,A Way Out,PS4,https://psdeals.net/ua-store/game/1480053/a-wa...,https://store.playstation.com/store/api/chihir...,"1,049.00₴",1
1,ASTRO BOT,PS5,https://psdeals.net/ua-store/game/2787643/astr...,https://store.playstation.com/store/api/chihir...,"1,999.00₴",1
2,Alan Wake Remastered,PS5 / PS4,https://psdeals.net/ua-store/game/2263208/alan...,https://store.playstation.com/store/api/chihir...,799.00₴,1
3,Alone in the Dark,PS5,https://psdeals.net/ua-store/game/2599714/alon...,https://store.playstation.com/store/api/chihir...,"1,799.00₴",1
4,Bendy and the Dark Revival,PS4,https://psdeals.net/ua-store/game/2554957/bend...,https://store.playstation.com/store/api/chihir...,929.00₴,1
5,Bendy and the Ink Machine,PS4,https://psdeals.net/ua-store/game/1653327/bend...,https://store.playstation.com/store/api/chihir...,649.00₴,1
6,Burnout™ Paradise Remastered,PS4,https://psdeals.net/ua-store/game/1474936/burn...,https://store.playstation.com/store/api/chihir...,649.00₴,1
7,Ctrl Alt Ego,PS5,https://psdeals.net/ua-store/game/2843851/ctrl...,https://store.playstation.com/store/api/chihir...,819.00₴,1
8,Cuphead and The Delicious Last Course,PS4,https://psdeals.net/ua-store/game/2404934/cuph...,https://store.playstation.com/store/api/chihir...,879.00₴,1
9,Cyberpunk 2077: Полное издание (PS5),PS5 / PS4,https://psdeals.net/ua-store/game/2607614/cybe...,https://store.playstation.com/store/api/chihir...,"2,299.00₴",1

# Delete duplicates

In [4]:
df = pd.read_csv(filename)
df.drop_duplicates(subset=['title', 'platform', 'psd_URL'], keep=False, inplace=True)
df.to_csv(filename, index=False)

In [5]:
df.head()

,title,platform,psd_URL,icon_URL,price,status
0,Techno Banter: Ultimate Mix,PS5,https://psdeals.net/ua-store/game/2873228/tech...,https://store.playstation.com/store/api/chihir...,649.00₴,0.0
1,"Warhammer 40,000: Darktide",PS5,https://psdeals.net/ua-store/game/2873227/warh...,https://store.playstation.com/store/api/chihir...,759.00₴,0.0
2,"Warhammer 40,000: Darktide - Imperial Edition",PS5,https://psdeals.net/ua-store/game/2873226/warh...,https://store.playstation.com/store/api/chihir...,"1,139.00₴",0.0
3,Techtonica,PS5,https://psdeals.net/ua-store/game/2873225/tech...,https://store.playstation.com/store/api/chihir...,999.00₴,0.0
4,Skydivers Paradise,PS4,https://psdeals.net/ua-store/game/2873224/skyd...,https://store.playstation.com/store/api/chihir...,64.00₴,0.0