In [4]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from datetime import datetime as dt
import traceback
import numpy as np

from config import filename

import warnings
warnings.filterwarnings("ignore")

# Filter subtitle

In [47]:
subtitles_to_remove = ["Arcade Archives",
                       "Warhammer",
                       "FINAL FANTASY",
                       "Disney",
                       "LEGO®",
                       "Funko Fusion",
                       "Outbreak:",
                       
                      ]

In [48]:
title_substring = subtitles_to_remove[-1]

df = pd.read_csv(filename)

for subtitle in subtitles_to_remove:
    df.loc[df[df['title'].str.contains(title_substring)].index, 'status'] = -1

df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)
df.to_csv(filename, index=False)

In [49]:
title_substring = subtitles_to_remove[-1]
df[df['title'].str.contains(title_substring)]

,title,platform,psd_URL,icon_URL,price,status
13582,Outbreak: Blood & Teeth Collection,PS4,https://psdeals.net/ua-store/game/2784113/outb...,https://store.playstation.com/store/api/chihir...,"2,299.00₴",-1
13583,Outbreak: Contagious Memories,PS4,https://psdeals.net/ua-store/game/2367294/outb...,https://store.playstation.com/store/api/chihir...,999.00₴,-1
13584,Outbreak: Contagious Memories,PS5,https://psdeals.net/ua-store/game/2367293/outb...,https://store.playstation.com/store/api/chihir...,999.00₴,-1
13585,Outbreak: Contagious Memories Definitive Colle...,PS4,https://psdeals.net/ua-store/game/2367295/outb...,https://store.playstation.com/store/api/chihir...,"1,699.00₴",-1
13586,Outbreak: Endless Nightmares,PS5,https://psdeals.net/ua-store/game/2201510/outb...,https://store.playstation.com/store/api/chihir...,649.00₴,-1
13587,Outbreak: Endless Nightmares,PS4,https://psdeals.net/ua-store/game/2201509/outb...,https://store.playstation.com/store/api/chihir...,649.00₴,-1
13588,Outbreak: Endless Nightmares Definitive Collec...,PS4,https://psdeals.net/ua-store/game/2365558/outb...,https://store.playstation.com/store/api/chihir...,"1,109.00₴",-1
13589,Outbreak: Epidemic,PS5,https://psdeals.net/ua-store/game/2145169/outb...,https://store.playstation.com/store/api/chihir...,489.00₴,-1
13590,Outbreak: Epidemic,PS4,https://psdeals.net/ua-store/game/2078758/outb...,https://store.playstation.com/store/api/chihir...,419.00₴,-1
13591,Outbreak: Epidemic Definitive Collection,PS4,https://psdeals.net/ua-store/game/2493763/outb...,https://store.playstation.com/store/api/chihir...,819.00₴,-1
13592,Outbreak: Lost Hope,PS5,https://psdeals.net/ua-store/game/2146594/outb...,https://store.playstation.com/store/api/chihir...,489.00₴,-1
13593,Outbreak: Lost Hope,PS4,https://psdeals.net/ua-store/game/2093254/outb...,https://store.playstation.com/store/api/chihir...,419.00₴,-1
13594,Outbreak: Lost Hope Definitive Collection,PS4,https://psdeals.net/ua-store/game/2508102/outb...,https://store.playstation.com/store/api/chihir...,819.00₴,-1
13595,Outbreak: Shades of Horror Chromatic Split,PS5 / PS4,https://psdeals.net/ua-store/game/2888111/outb...,https://store.playstation.com/store/api/chihir...,"4,799.00₴",-1
13596,Outbreak: Shades of Horror Chromatic Split,PS5,https://psdeals.net/ua-store/game/2886118/outb...,https://store.playstation.com/store/api/chihir...,"2,999.00₴",-1
13597,Outbreak: Shades of Horror Chromatic Split,PS5,https://psdeals.net/ua-store/game/2885260/outb...,https://store.playstation.com/store/api/chihir...,"1,499.00₴",-1
13598,Outbreak: Shades of Horror Chromatic Split,PS5,https://psdeals.net/ua-store/game/2881666/outb...,https://store.playstation.com/store/api/chihir...,"2,199.00₴",-1
13599,Outbreak: The New Nightmare,PS5,https://psdeals.net/ua-store/game/2141791/outb...,https://store.playstation.com/store/api/chihir...,489.00₴,-1
13600,Outbreak: The New Nightmare,PS4,https://psdeals.net/ua-store/game/2072204/outb...,https://store.playstation.com/store/api/chihir...,419.00₴,-1
13601,Outbreak: The New Nightmare Definitive Collection,PS4,https://psdeals.net/ua-store/game/2499455/outb...,https://store.playstation.com/store/api/chihir...,819.00₴,-1
13602,Outbreak: The Nightmare Chronicles,PS5,https://psdeals.net/ua-store/game/2146032/outb...,https://store.playstation.com/store/api/chihir...,489.00₴,-1
13603,Outbreak: The Nightmare Chronicles,PS4,https://psdeals.net/ua-store/game/2085910/outb...,https://store.playstation.com/store/api/chihir...,419.00₴,-1
13604,Outbreak: The Nightmare Chronicles Definitive ...,PS4,https://psdeals.net/ua-store/game/2504496/outb...,https://store.playstation.com/store/api/chihir...,819.00₴,-1

# Delete publisher

In [6]:
def get_pub(publisher):
    
    time = dt.now()
    
    page_num = 1
    df_pub = pd.DataFrame(columns=['title', 'platform', "psd_URL", "icon_URL", "price"])

    prev_page = None

    while True:
        try:
            URL = f"https://psdeals.net/ua-store/all-games/{page_num}?publisher={publisher}"
            #URL = f"https://psdeals.net/ua-store/all-games{page_num}?contentType%5B%5D=games&contentType%5B%5D=bundles&feature%5B%5D=vrGames"

            headers = requests.utils.default_headers()
            page = requests.get(URL, headers=headers)

            soup = BeautifulSoup(page.content, "html.parser")

            grid_items = soup.find_all('div', class_='game-collection-item col-md-2 col-sm-4 col-xs-6')

            if grid_items == prev_page:
                break

            for item in grid_items:

                title = item.find('span', class_='game-collection-item-details-title').text
                platform = item.find('span', class_='game-collection-item-top-platform').text
                image = item.find('img', class_='game-collection-item-image lazy').get('data-src')
                psd_link = "https://psdeals.net" + item.find('a', class_='game-collection-item-link').get('href')

                try:
                    price = item.find('span', class_='game-collection-item-price').text
                except:
                    price = np.NaN

                new_row = {"title": title, 
                           "platform": platform,
                           "price": price,
                           "psd_URL": psd_link,
                           "icon_URL": image}


                df_pub = df_pub.append(new_row, ignore_index=True)

            print(f"page {page_num}  time {dt.now() - time}")

            page_num += 1

            prev_page = grid_items

        except Exception as e:
            print(e)
            print(traceback.format_exc())
            break
            
    return df_pub

In [42]:
bad_publishers_list = ["Kanuni+games+oyun+YAZILIM+VE+Pazarlama+Ticaret+limited+Sirketi",
                       "Kimulator%27s+Films+inc.",
                       "MARKT%2BTECHNIK+VERLAG+GMBH",
                       "NOSTRA+GAMES+LTD",
                       "JOINDOTS+GMBH",
                       "SMOBILE+INC",
                       "KODOBUR+YAZILIM+BILISIM+TASARIM+ARG",
                       "ThiGames",
                       "Entalto+Games+SL",
                       "OÜ+Enningture+Game+Temple",
                       "Gametry+sp.+z+o.+o.",
                       "QUBICGAMES+SP.+Z+O.O.",
                       "Klovako+s.+r.+o.",
                       "Benoit+Varasse+trading+as+Pix+Arts",
                       "Game+Achievements+Ltd",
                       "Zakym+s.+r.+o.",
                       "Acyntha",
                       "CLICKTEAM+LLC+USA",
                       "Webnetic+s.+r.+o.",
                       "Scout+Game+Studios+Sociedad+Anonima",
                       "THOMAS+CLAUS+UND+FRANK+MENZEL",
                       "Microids",
                       "EVGENIY+KOLPAKOV",
                       "QUBYTE+INTERACTIVE",
                       "Feardemic",
                       "Aristo+Studio+s.r.o.",
                       "RECOTECHNOLOGY+S.L.",
                       "We+Dig+Games+sp.+z+o.o.",
                       "OCEAN+MEDIA+LLC",
                       "Breakthrough+Gaming+LLC",
                       "Wales+Interactive+Limited",
                       "ONSKULL+DEVELOPMENT",
                       "Xitilon",
                       "Nellyvision+Ltd",
                       
                      
                      ]

In [43]:
publisher = bad_publishers_list[-1]

df_pub = get_pub(publisher)        

df = pd.read_csv(filename)

df.loc[df[df['title'].isin(df_pub.title)].index, 'status'] = -1
df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)
df.to_csv(filename, index=False)

page 1  time 0:00:00.936358

# Sort

In [3]:
df = pd.read_csv(filename)
df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)
df.to_csv(filename, index=False)

In [7]:
df.head(10)

,title,platform,psd_URL,icon_URL,price,status
0,A Way Out,PS4,https://psdeals.net/ua-store/game/1480053/a-wa...,https://store.playstation.com/store/api/chihir...,"1,049.00₴",1
1,ASTRO BOT,PS5,https://psdeals.net/ua-store/game/2787643/astr...,https://store.playstation.com/store/api/chihir...,"1,999.00₴",1
2,Alan Wake Remastered,PS5 / PS4,https://psdeals.net/ua-store/game/2263208/alan...,https://store.playstation.com/store/api/chihir...,799.00₴,1
3,Alone in the Dark,PS5,https://psdeals.net/ua-store/game/2599714/alon...,https://store.playstation.com/store/api/chihir...,"1,799.00₴",1
4,Bendy and the Dark Revival,PS4,https://psdeals.net/ua-store/game/2554957/bend...,https://store.playstation.com/store/api/chihir...,929.00₴,1
5,Bendy and the Ink Machine,PS4,https://psdeals.net/ua-store/game/1653327/bend...,https://store.playstation.com/store/api/chihir...,649.00₴,1
6,Burnout™ Paradise Remastered,PS4,https://psdeals.net/ua-store/game/1474936/burn...,https://store.playstation.com/store/api/chihir...,649.00₴,1
7,Ctrl Alt Ego,PS5,https://psdeals.net/ua-store/game/2843851/ctrl...,https://store.playstation.com/store/api/chihir...,819.00₴,1
8,Cuphead and The Delicious Last Course,PS4,https://psdeals.net/ua-store/game/2404934/cuph...,https://store.playstation.com/store/api/chihir...,879.00₴,1
9,Cyberpunk 2077: Полное издание (PS5),PS5 / PS4,https://psdeals.net/ua-store/game/2607614/cybe...,https://store.playstation.com/store/api/chihir...,"2,299.00₴",1

# Delete duplicates

In [4]:
df = pd.read_csv(filename)
df.drop_duplicates(subset=['title', 'platform', 'psd_URL'], keep=False, inplace=True)
df.to_csv(filename, index=False)

In [5]:
df.head()

,title,platform,psd_URL,icon_URL,price,status
0,Techno Banter: Ultimate Mix,PS5,https://psdeals.net/ua-store/game/2873228/tech...,https://store.playstation.com/store/api/chihir...,649.00₴,0.0
1,"Warhammer 40,000: Darktide",PS5,https://psdeals.net/ua-store/game/2873227/warh...,https://store.playstation.com/store/api/chihir...,759.00₴,0.0
2,"Warhammer 40,000: Darktide - Imperial Edition",PS5,https://psdeals.net/ua-store/game/2873226/warh...,https://store.playstation.com/store/api/chihir...,"1,139.00₴",0.0
3,Techtonica,PS5,https://psdeals.net/ua-store/game/2873225/tech...,https://store.playstation.com/store/api/chihir...,999.00₴,0.0
4,Skydivers Paradise,PS4,https://psdeals.net/ua-store/game/2873224/skyd...,https://store.playstation.com/store/api/chihir...,64.00₴,0.0

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv(filename)