In [6]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from datetime import datetime as dt
import traceback
import numpy as np

from config import filename

import warnings
warnings.filterwarnings("ignore")

In [7]:
df = pd.DataFrame(columns=['title', 'platform', "price", "psd_URL", "icon_URL", "status"])

compare_old = False

In [9]:
if compare_old:
    try:
        df_previous = pd.read_csv(filename)
    except FileNotFoundError:
        print("file not found")
        compare_old = False

In [10]:
time = dt.now()

page_num = 1
df = pd.DataFrame(columns=['title', 'platform', "psd_URL", "icon_URL", "price", "status"])

prev_page = None

while True:
    try:
        URL = f"https://psdeals.net/ua-store/all-games/{page_num}"

        headers = requests.utils.default_headers()
        page = requests.get(URL, headers=headers)

        soup = BeautifulSoup(page.content, "html.parser")

        grid_items = soup.find_all('div', class_='game-collection-item col-md-2 col-sm-4 col-xs-6')
        
        if grid_items == prev_page:
            break

        for item in grid_items:
            
            title = item.find('span', class_='game-collection-item-details-title').text
            platform = item.find('span', class_='game-collection-item-top-platform').text
            image = item.find('img', class_='game-collection-item-image lazy').get('data-src')
            psd_link = "https://psdeals.net" + item.find('a', class_='game-collection-item-link').get('href')
            
            try:
                price = item.find('span', class_='game-collection-item-price').text
            except:
                price = np.NaN
            
            new_row = {"title": title, 
                       "platform": platform,
                       "price": price,
                       "psd_URL": psd_link,
                       "icon_URL": image}


            df = df.append(new_row, ignore_index=True)

        print(f"page {page_num}  time {dt.now() - time}")
        
        page_num += 1
        
        prev_page = grid_items
        
    except Exception as e:
        print(e)
        print(traceback.format_exc())
        break

page 1  time 0:00:01.844422
page 2  time 0:00:03.814373
page 3  time 0:00:05.553263
page 4  time 0:00:07.377726
page 5  time 0:00:09.274466
page 6  time 0:00:11.125318
page 7  time 0:00:12.707273
page 8  time 0:00:14.243466
page 9  time 0:00:16.388886
page 10  time 0:00:18.153543
page 11  time 0:00:19.675717
page 12  time 0:00:21.143762
page 13  time 0:00:22.582689
page 14  time 0:00:24.112652
page 15  time 0:00:25.707521
page 16  time 0:00:27.126973
page 17  time 0:00:28.628061
page 18  time 0:00:30.145439
page 19  time 0:00:31.657793
page 20  time 0:00:33.190919
page 21  time 0:00:34.731309
page 22  time 0:00:36.280252
page 23  time 0:00:37.794427
page 24  time 0:00:39.335329
page 25  time 0:00:40.824914
page 26  time 0:00:42.353332
page 27  time 0:00:43.824682
page 28  time 0:00:45.349574
page 29  time 0:00:46.882948
page 30  time 0:00:48.484243
page 31  time 0:00:50.095336
page 32  time 0:00:51.564395
page 33  time 0:00:53.055505
page 34  time 0:00:54.648223
page 35  time 0:00:56.260469
page 36  time 0:00:57.850058
page 37  time 0:00:59.398376
page 38  time 0:01:00.993234
page 39  time 0:01:02.454228
page 40  time 0:01:04.025338
page 41  time 0:01:05.570768
page 42  time 0:01:07.019593
page 43  time 0:01:08.633536
page 44  time 0:01:10.268620
page 45  time 0:01:12.123010
page 46  time 0:01:14.411352
page 47  time 0:01:16.640047
page 48  time 0:01:18.226877
page 49  time 0:01:20.007460
page 50  time 0:01:21.549985
page 51  time 0:01:23.160847
page 52  time 0:01:24.733871
page 53  time 0:01:26.360525
page 54  time 0:01:27.996477
page 55  time 0:01:29.659680
page 56  time 0:01:31.215355
page 57  time 0:01:32.893655
page 58  time 0:01:34.654780
page 59  time 0:01:36.215420
page 60  time 0:01:37.806760
page 61  time 0:01:39.577143
page 62  time 0:01:41.204198
page 63  time 0:01:42.804447
page 64  time 0:01:44.351919
page 65  time 0:01:45.928219
page 66  time 0:01:47.564433
page 67  time 0:01:49.173150
page 68  time 0:01:50.792957
page 69  time 0:01:52.474469
page 70  time 0:01:54.093936
page 71  time 0:01:55.786034
page 72  time 0:01:57.412897
page 73  time 0:01:58.958585
page 74  time 0:02:00.565375
page 75  time 0:02:02.093872
page 76  time 0:02:03.622121
page 77  time 0:02:05.209846
page 78  time 0:02:06.759926
page 79  time 0:02:08.501000
page 80  time 0:02:10.311290
page 81  time 0:02:12.113610
page 82  time 0:02:13.645855
page 83  time 0:02:15.367304
page 84  time 0:02:16.969189
page 85  time 0:02:18.600430
page 86  time 0:02:20.187218
page 87  time 0:02:21.894032
page 88  time 0:02:23.507697
page 89  time 0:02:25.124077
page 90  time 0:02:26.693588
page 91  time 0:02:28.366317
page 92  time 0:02:29.957634
page 93  time 0:02:31.683242
page 94  time 0:02:33.351487
page 95  time 0:02:35.025015
page 96  time 0:02:36.540923
page 97  time 0:02:38.147066
page 98  time 0:02:39.914143
page 99  time 0:02:41.585020
page 100  time 0:02:43.186184
page 101  time 0:02:44.841841
page 102  time 0:02:46.563291
page 103  time 0:02:48.370933
page 104  time 0:02:50.012328
page 105  time 0:02:51.537485
page 106  time 0:02:53.415189
page 107  time 0:02:55.081497
page 108  time 0:02:56.627923
page 109  time 0:02:58.203175
page 110  time 0:02:59.787239
page 111  time 0:03:01.356146
page 112  time 0:03:02.908182
page 113  time 0:03:04.540540
page 114  time 0:03:06.238461
page 115  time 0:03:07.896129
page 116  time 0:03:09.620754
page 117  time 0:03:11.466504
page 118  time 0:03:13.017970
page 119  time 0:03:14.553176
page 120  time 0:03:16.159235
page 121  time 0:03:17.812128
page 122  time 0:03:19.394074
page 123  time 0:03:21.125608
page 124  time 0:03:22.836202
page 125  time 0:03:24.506081
page 126  time 0:03:26.149413
page 127  time 0:03:27.807305
page 128  time 0:03:29.415539
page 129  time 0:03:31.081879
page 130  time 0:03:32.660776
page 131  time 0:03:34.437248
page 132  time 0:03:36.239129
page 133  time 0:03:37.959731
page 134  time 0:03:39.617633
page 135  time 0:03:41.321203
page 136  time 0:03:42.916222
page 137  time 0:03:44.566192
page 138  time 0:03:46.216210
page 139  time 0:03:47.901167
page 140  time 0:03:49.674811
page 141  time 0:03:51.407049
page 142  time 0:03:53.215551
page 143  time 0:03:54.819224
page 144  time 0:03:56.530051
page 145  time 0:03:58.076929
page 146  time 0:03:59.762028
page 147  time 0:04:01.456777
page 148  time 0:04:03.325502
page 149  time 0:04:04.958098
page 150  time 0:04:06.538320
page 151  time 0:04:08.180783
page 152  time 0:04:09.751044
page 153  time 0:04:11.597604
page 154  time 0:04:13.310837
page 155  time 0:04:15.001295
page 156  time 0:04:16.828577
page 157  time 0:04:18.665905
page 158  time 0:04:20.439348
page 159  time 0:04:22.354816
page 160  time 0:04:24.016217
page 161  time 0:04:26.840644
page 162  time 0:04:28.630948
page 163  time 0:04:30.296281
page 164  time 0:04:32.018841
page 165  time 0:04:33.761110
page 166  time 0:04:35.469513
page 167  time 0:04:37.151373
page 168  time 0:04:38.839185
page 169  time 0:04:40.585810
page 170  time 0:04:42.324201
page 171  time 0:04:44.046420
page 172  time 0:04:45.736074
page 173  time 0:04:47.349972
page 174  time 0:04:49.149918
page 175  time 0:04:50.873980
page 176  time 0:04:52.866937
page 177  time 0:04:54.549712
page 178  time 0:04:56.228749
page 179  time 0:04:58.003698
page 180  time 0:04:59.678249
page 181  time 0:05:01.442419
page 182  time 0:05:03.100056
page 183  time 0:05:04.862594
page 184  time 0:05:06.558496
page 185  time 0:05:08.242803
page 186  time 0:05:10.215651
page 187  time 0:05:11.823318
page 188  time 0:05:13.680679
page 189  time 0:05:15.387650
page 190  time 0:05:17.075359
page 191  time 0:05:18.744079
page 192  time 0:05:20.489750
page 193  time 0:05:22.229671
page 194  time 0:05:23.979202
page 195  time 0:05:25.682564
page 196  time 0:05:27.360318
page 197  time 0:05:29.066800
page 198  time 0:05:30.801829
page 199  time 0:05:32.507561
page 200  time 0:05:34.201038
page 201  time 0:05:36.041332
page 202  time 0:05:37.968216
page 203  time 0:05:39.763070
page 204  time 0:05:41.600734
page 205  time 0:05:43.417266
page 206  time 0:05:45.147795
page 207  time 0:05:46.888502
page 208  time 0:05:48.605513
page 209  time 0:05:50.484014
page 210  time 0:05:52.286079
page 211  time 0:05:54.098449
page 212  time 0:05:55.779411
page 213  time 0:05:57.637371
page 214  time 0:05:59.466754
page 215  time 0:06:01.137049
page 216  time 0:06:02.802492
page 217  time 0:06:04.514663
page 218  time 0:06:06.325748
page 219  time 0:06:08.211863
page 220  time 0:06:10.018953
page 221  time 0:06:11.697561
page 222  time 0:06:13.373350
page 223  time 0:06:14.999793
page 224  time 0:06:16.991817
page 225  time 0:06:18.863830
page 226  time 0:06:20.685737
page 227  time 0:06:22.446505
page 228  time 0:06:24.256732
page 229  time 0:06:26.134805
page 230  time 0:06:28.002149
page 231  time 0:06:29.757552
page 232  time 0:06:31.544295
page 233  time 0:06:33.356622
page 234  time 0:06:35.086743
page 235  time 0:06:36.856559
page 236  time 0:06:38.599791
page 237  time 0:06:40.348490
page 238  time 0:06:42.202672
page 239  time 0:06:44.024780
page 240  time 0:06:46.013789
page 241  time 0:06:47.751197
page 242  time 0:06:49.405873
page 243  time 0:06:51.155785
page 244  time 0:06:52.943481
page 245  time 0:06:54.897514
page 246  time 0:06:56.834410
page 247  time 0:06:58.680794
page 248  time 0:07:00.624793
page 249  time 0:07:02.485066
page 250  time 0:07:04.310518
page 251  time 0:07:05.975665
page 252  time 0:07:07.770418
page 253  time 0:07:09.517501
page 254  time 0:07:11.276962
page 255  time 0:07:13.006649
page 256  time 0:07:14.820445
page 257  time 0:07:16.646423
page 258  time 0:07:18.455984
page 259  time 0:07:20.262425
page 260  time 0:07:22.140070
page 261  time 0:07:23.906621
page 262  time 0:07:25.759026
page 263  time 0:07:27.640356
page 264  time 0:07:29.426624
page 265  time 0:07:31.357791
page 266  time 0:07:33.588312
page 267  time 0:07:35.346673
page 268  time 0:07:37.205877
page 269  time 0:07:39.025576
page 270  time 0:07:40.832981
page 271  time 0:07:42.634120
page 272  time 0:07:44.477720
page 273  time 0:07:46.260557
page 274  time 0:07:48.104041
page 275  time 0:07:49.890731
page 276  time 0:07:51.738792
page 277  time 0:07:53.642397

page 278  time 0:07:55.440188
page 279  time 0:07:57.271665
page 280  time 0:07:59.059021
page 281  time 0:08:00.842148
page 282  time 0:08:02.721848
page 283  time 0:08:04.430002
page 284  time 0:08:06.213054
page 285  time 0:08:08.334150
page 286  time 0:08:10.524954
page 287  time 0:08:12.327387
page 288  time 0:08:14.108940
page 289  time 0:08:15.848054
page 290  time 0:08:17.567684
page 291  time 0:08:19.497631
page 292  time 0:08:21.447731
page 293  time 0:08:23.389215
page 294  time 0:08:25.174288
page 295  time 0:08:26.954882
page 296  time 0:08:28.815764
page 297  time 0:08:30.685326
page 298  time 0:08:32.662084
page 299  time 0:08:34.542547
page 300  time 0:08:36.348840
page 301  time 0:08:38.127738
page 302  time 0:08:40.104000
page 303  time 0:08:41.972495
page 304  time 0:08:43.780014
page 305  time 0:08:45.540453
page 306  time 0:08:47.550223
page 307  time 0:08:49.486649
page 308  time 0:08:51.305546
page 309  time 0:08:53.036842
page 310  time 0:08:55.129947
page 311  time 0:08:57.105263
page 312  time 0:08:59.139875
page 313  time 0:09:01.087782
page 314  time 0:09:03.320273
page 315  time 0:09:05.198561
page 316  time 0:09:07.433999
page 317  time 0:09:09.385388
page 318  time 0:09:11.697920
page 319  time 0:09:14.031529
page 320  time 0:09:15.831803
page 321  time 0:09:17.887524
page 322  time 0:09:19.869127
page 323  time 0:09:21.769197
page 324  time 0:09:23.624304
page 325  time 0:09:25.384032
page 326  time 0:09:27.299782
page 327  time 0:09:29.152553
page 328  time 0:09:31.216943
page 329  time 0:09:33.153933
page 330  time 0:09:35.100503
page 331  time 0:09:37.034617
page 332  time 0:09:38.856039
page 333  time 0:09:40.787917
page 334  time 0:09:42.583287
page 335  time 0:09:44.433936
page 336  time 0:09:46.341922
page 337  time 0:09:48.371006
page 338  time 0:09:50.173298
page 339  time 0:09:52.034747
page 340  time 0:09:53.879611
page 341  time 0:09:55.848978
page 342  time 0:09:57.713722
page 343  time 0:09:59.586053
page 344  time 0:10:01.810224
page 345  time 0:10:03.734518
page 346  time 0:10:05.549085
page 347  time 0:10:07.367200
page 348  time 0:10:09.311125
page 349  time 0:10:11.400299
page 350  time 0:10:13.414410
page 351  time 0:10:15.247654
page 352  time 0:10:17.197958
page 353  time 0:10:19.340859
page 354  time 0:10:21.506576
page 355  time 0:10:23.429678
page 356  time 0:10:25.393960
page 357  time 0:10:27.351642
page 358  time 0:10:29.190693
page 359  time 0:10:31.337847
page 360  time 0:10:33.182128
page 361  time 0:10:35.154960
page 362  time 0:10:37.278959
page 363  time 0:10:39.140590
page 364  time 0:10:41.045333
page 365  time 0:10:43.028166
page 366  time 0:10:44.865349
page 367  time 0:10:46.698168
page 368  time 0:10:48.646678
page 369  time 0:10:50.569649
page 370  time 0:10:52.540643
page 371  time 0:10:54.463465
page 372  time 0:10:56.363456
page 373  time 0:10:58.348539
page 374  time 0:11:00.320314
page 375  time 0:11:02.251562
page 376  time 0:11:04.220856
page 377  time 0:11:06.188643
page 378  time 0:11:08.051802
page 379  time 0:11:09.955752
page 380  time 0:11:11.860930
page 381  time 0:11:13.778854
page 382  time 0:11:15.933372
page 383  time 0:11:17.833945
page 384  time 0:11:19.761933
page 385  time 0:11:21.730439
page 386  time 0:11:23.651255
page 387  time 0:11:25.599170
page 388  time 0:11:27.459246
page 389  time 0:11:29.404597
page 390  time 0:11:31.221221
page 391  time 0:11:33.180369
page 392  time 0:11:35.127725
page 393  time 0:11:37.143275
page 394  time 0:11:39.082419
page 395  time 0:11:41.005891
page 396  time 0:11:43.424217
page 397  time 0:11:45.418287
page 398  time 0:11:47.431741
page 399  time 0:11:49.396033
page 400  time 0:11:51.250991
page 401  time 0:11:53.197624
page 402  time 0:11:55.017420
page 403  time 0:11:57.038536
page 404  time 0:11:58.994914
page 405  time 0:12:01.007485
page 406  time 0:12:02.955877
page 407  time 0:12:04.829192
page 408  time 0:12:06.716569
page 409  time 0:12:08.654523
page 410  time 0:12:10.672241
page 411  time 0:12:12.624605
page 412  time 0:12:14.457967
page 413  time 0:12:16.427283
page 414  time 0:12:18.442772
page 415  time 0:12:20.371051
page 416  time 0:12:22.755251
page 417  time 0:12:24.716196
page 418  time 0:12:26.663594
page 419  time 0:12:28.675458
page 420  time 0:12:30.768360
page 421  time 0:12:32.636221
page 422  time 0:12:34.469668
page 423  time 0:12:36.496508
page 424  time 0:12:38.571609
page 425  time 0:12:40.574664
page 426  time 0:12:42.517184
page 427  time 0:12:44.396357
page 428  time 0:12:46.186447
page 429  time 0:12:48.102623
page 430  time 0:12:50.087367
page 431  time 0:12:52.033218
page 432  time 0:12:54.140722
page 433  time 0:12:56.174497
page 434  time 0:12:57.985687
page 435  time 0:12:59.938055
page 436  time 0:13:01.834667
page 437  time 0:13:03.800223
page 438  time 0:13:05.592571
page 439  time 0:13:07.571191
page 440  time 0:13:09.565402
page 441  time 0:13:11.545524
page 442  time 0:13:13.935563
page 443  time 0:13:15.897891
page 444  time 0:13:17.762938
page 445  time 0:13:19.843081
page 446  time 0:13:21.757797
page 447  time 0:13:23.703475
page 448  time 0:13:25.508083
page 449  time 0:13:27.527695
page 450  time 0:13:28.226421
page 451  time 0:13:30.197030
page 452  time 0:13:32.063534
page 453  time 0:13:34.099445
page 454  time 0:13:36.517579
page 455  time 0:13:38.576619
page 456  time 0:13:40.724957
page 457  time 0:13:42.702037
page 458  time 0:13:44.650522
page 459  time 0:13:46.815512
page 460  time 0:13:48.807230
page 461  time 0:13:50.765147
page 462  time 0:13:52.584996
page 463  time 0:13:54.553554
page 464  time 0:13:56.558458
page 465  time 0:13:58.485941
page 466  time 0:14:00.487778
page 467  time 0:14:02.471989
page 468  time 0:14:04.420873
page 469  time 0:14:06.444723
page 470  time 0:14:08.413870
page 471  time 0:14:10.417665
page 472  time 0:14:12.369603
page 473  time 0:14:14.280455
page 474  time 0:14:16.323525
page 475  time 0:14:18.372288
page 476  time 0:14:20.497940
page 477  time 0:14:22.552834
page 478  time 0:14:24.567382
page 479  time 0:14:26.576958
page 480  time 0:14:28.789901
page 481  time 0:14:30.862392
page 482  time 0:14:32.960346
page 483  time 0:14:34.954178
page 484  time 0:14:37.015415
page 485  time 0:14:39.028337
page 486  time 0:14:40.979439
page 487  time 0:14:42.999772
page 488  time 0:14:44.837013
page 489  time 0:14:45.371089

In [11]:
df.head()

,title,platform,psd_URL,icon_URL,price,status
0,Cat From Hell - Cat Simulator,PS4,https://psdeals.net/ua-store/game/2970634/cat-...,https://store.playstation.com/store/api/chihir...,159.00₴,NaN
1,Cat From Hell - Cat Simulator,PS5,https://psdeals.net/ua-store/game/2970632/cat-...,https://store.playstation.com/store/api/chihir...,159.00₴,NaN
2,Sqwrk,PS4,https://psdeals.net/ua-store/game/2970630/sqwrk,https://store.playstation.com/store/api/chihir...,15.00₴,NaN
3,Hell Froze Over PS4® & PS5®,PS5 / PS4,https://psdeals.net/ua-store/game/2970629/hell...,https://store.playstation.com/store/api/chihir...,99.00₴,NaN
4,Toy Drop Balance Challenge,PS5 / PS4,https://psdeals.net/ua-store/game/2969718/toy-...,https://store.playstation.com/store/api/chihir...,129.00₴,NaN

delete_lst = ['PS3', 'PS Vita', 'PS3 / PS Vita / PSP', 
              'PS Vita / PSP', 'PS3 / PS Vita', 'PS3 / PSP', 'PSP' ]

for del_pl in delete_lst:
    df = df[df.platform != del_pl]

In [12]:
if compare_old:
    df_res = pd.merge(df, df_previous, on=['title', 'platform', 'psd_URL'], how='outer')
    df_res['status'] = df_res[['status_x', 'status_y']].max(axis=1).fillna(0) 
    df_res['price'] = df_res['price_x'].combine_first(df_res['price_y'])
    #df_res['psd_URL'] = df_res['psd_URL_x'].combine_first(df_res['psd_URL_y'])
    df_res['icon_URL'] = df_res['icon_URL_x'].combine_first(df_res['icon_URL_y'])
    df_res.drop(['status_x', 'status_y', 
                  'price_x', 'price_y', 
                  'icon_URL_y', 'icon_URL_x'], inplace=True, axis=1)
    
    df_res = df_res[['title', 'platform', 'psd_URL', 'icon_URL', 'price', 'status']]
else:
    df_res = df
    df_res['status'] = 0
    
# df = df.drop_duplicates(subset=['title', 'platform', 'psd_URL'], keep=False)
df = df.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)

In [13]:
df_res.head(5)

,title,platform,psd_URL,icon_URL,price,status
0,Cat From Hell - Cat Simulator,PS4,https://psdeals.net/ua-store/game/2970634/cat-...,https://store.playstation.com/store/api/chihir...,159.00₴,0
1,Cat From Hell - Cat Simulator,PS5,https://psdeals.net/ua-store/game/2970632/cat-...,https://store.playstation.com/store/api/chihir...,159.00₴,0
2,Sqwrk,PS4,https://psdeals.net/ua-store/game/2970630/sqwrk,https://store.playstation.com/store/api/chihir...,15.00₴,0
3,Hell Froze Over PS4® & PS5®,PS5 / PS4,https://psdeals.net/ua-store/game/2970629/hell...,https://store.playstation.com/store/api/chihir...,99.00₴,0
4,Toy Drop Balance Challenge,PS5 / PS4,https://psdeals.net/ua-store/game/2969718/toy-...,https://store.playstation.com/store/api/chihir...,129.00₴,0

In [14]:
df_res.shape

(17583, 6)

In [16]:
try:
    df_previous.shape
except Exception:
    pass

In [15]:
df_res.to_csv(filename, index=False)