In [1]:
import pandas as pd

import cloudscraper
from bs4 import BeautifulSoup
from datetime import datetime as dt
import traceback
import numpy as np

from config import filename

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.DataFrame(columns=['title', 'platform', "price", "psd_URL", "icon_URL", "status"])

compare_old = False

In [3]:
if compare_old:
    try:
        df_previous = pd.read_csv(filename)
    except FileNotFoundError:
        print("file not found")
        compare_old = False

In [4]:
time = dt.now()

page_num = 1
df = pd.DataFrame(columns=['title', 'platform', "psd_URL", "icon_URL", "price", "status"])

prev_page = None

scraper = cloudscraper.create_scraper()

while True:
    try:

        response = scraper.get(f"https://psdeals.net/ua-store/all-games/{page_num}")

        soup = BeautifulSoup(response.text, "html.parser")

        grid_items = soup.find_all('div', class_='game-collection-item col-md-2 col-sm-4 col-xs-6')
        
        if grid_items == prev_page:
            break

        for item in grid_items:
            
            title = item.find('span', class_='game-collection-item-details-title').text
            platform = item.find('span', class_='game-collection-item-top-platform').text
            image = item.find('img', class_='game-collection-item-image lazy').get('data-src')
            psd_link = "https://psdeals.net" + item.find('a', class_='game-collection-item-link').get('href')
            
            try:
                price = item.find('span', class_='game-collection-item-price').text
            except:
                price = np.NaN
            
            new_row = {"title": title, 
                       "platform": platform,
                       "price": price,
                       "psd_URL": psd_link,
                       "icon_URL": image}

            df = df.append(new_row, ignore_index=True)

        print(f"page {page_num}  time {dt.now() - time}")
        
        page_num += 1
        
        prev_page = grid_items
        
    except Exception as e:
        print(e)
        print(traceback.format_exc())
        break

page 1  time 0:00:00.821850
page 2  time 0:00:02.609122
page 3  time 0:00:04.131726
page 4  time 0:00:05.581373
page 5  time 0:00:07.202172
page 6  time 0:00:08.712157
page 7  time 0:00:10.714458
page 8  time 0:00:12.811080
page 9  time 0:00:14.419298
page 10  time 0:00:16.079071
page 11  time 0:00:17.586023
page 12  time 0:00:19.044880
page 13  time 0:00:20.521519
page 14  time 0:00:22.085780
page 15  time 0:00:23.793820
page 16  time 0:00:25.269077
page 17  time 0:00:26.873127
page 18  time 0:00:28.375300
page 19  time 0:00:29.925713
page 20  time 0:00:31.501877
page 21  time 0:00:33.113890
page 22  time 0:00:34.683743
page 23  time 0:00:36.295305
page 24  time 0:00:37.837326
page 25  time 0:00:39.472635
page 26  time 0:00:41.038309
page 27  time 0:00:42.648197
page 28  time 0:00:44.182199
page 29  time 0:00:45.684419
page 30  time 0:00:47.283104
page 31  time 0:00:48.820886
page 32  time 0:00:50.434217
page 33  time 0:00:51.916537
page 34  time 0:00:53.529610
page 35  time 0:00:55.018539
page 36  time 0:00:56.498361
page 37  time 0:00:57.970663
page 38  time 0:00:59.482701
page 39  time 0:01:00.979572
page 40  time 0:01:02.450944
page 41  time 0:01:03.923571
page 42  time 0:01:05.446899
page 43  time 0:01:06.905184
page 44  time 0:01:08.422291
page 45  time 0:01:09.996963
page 46  time 0:01:11.553953
page 47  time 0:01:13.099076
page 48  time 0:01:14.710746
page 49  time 0:01:16.246507
page 50  time 0:01:17.795245
page 51  time 0:01:19.265123
page 52  time 0:01:20.750762
page 53  time 0:01:22.291312
page 54  time 0:01:23.958360
page 55  time 0:01:25.418407
page 56  time 0:01:26.902238
page 57  time 0:01:28.486074
page 58  time 0:01:30.097394
page 59  time 0:01:31.565277
page 60  time 0:01:33.110062
page 61  time 0:01:34.686776
page 62  time 0:01:36.210115
page 63  time 0:01:37.724493
page 64  time 0:01:39.201729
page 65  time 0:01:40.840347
page 66  time 0:01:42.501843
page 67  time 0:01:44.113049
page 68  time 0:01:45.746769
page 69  time 0:01:47.388809
page 70  time 0:01:49.048700
page 71  time 0:01:50.617444
page 72  time 0:01:52.408233
page 73  time 0:01:53.919903
page 74  time 0:01:55.514675
page 75  time 0:01:57.047891
page 76  time 0:01:58.535620
page 77  time 0:02:00.094308
page 78  time 0:02:01.681225
page 79  time 0:02:03.195709
page 80  time 0:02:04.776132
page 81  time 0:02:06.362310
page 82  time 0:02:08.010400
page 83  time 0:02:09.720102
page 84  time 0:02:11.564444
page 85  time 0:02:13.209654
page 86  time 0:02:14.875280
page 87  time 0:02:16.419536
page 88  time 0:02:17.919649
page 89  time 0:02:19.505133
page 90  time 0:02:21.232720
page 91  time 0:02:22.780546
page 92  time 0:02:24.317595
page 93  time 0:02:25.919946
page 94  time 0:02:27.507491
page 95  time 0:02:29.069944
page 96  time 0:02:30.570119
page 97  time 0:02:32.090554
page 98  time 0:02:33.686047
page 99  time 0:02:35.435527
page 100  time 0:02:37.054029
page 101  time 0:02:38.652445
page 102  time 0:02:40.261529
page 103  time 0:02:41.892445
page 104  time 0:02:43.434255
page 105  time 0:02:44.913447
page 106  time 0:02:46.498975
page 107  time 0:02:48.169589
page 108  time 0:02:49.819510
page 109  time 0:02:51.319264
page 110  time 0:02:52.849135
page 111  time 0:02:54.513986
page 112  time 0:02:56.148768
page 113  time 0:02:57.875934
page 114  time 0:02:59.500546
page 115  time 0:03:01.027977
page 116  time 0:03:02.688680
page 117  time 0:03:04.373475
page 118  time 0:03:05.962217
page 119  time 0:03:07.633717
page 120  time 0:03:09.345696
page 121  time 0:03:10.972896
page 122  time 0:03:12.597061
page 123  time 0:03:14.321892
page 124  time 0:03:15.891592
page 125  time 0:03:17.429697
page 126  time 0:03:19.106437
page 127  time 0:03:20.592018
page 128  time 0:03:22.030132
page 129  time 0:03:23.546778
page 130  time 0:03:25.062458
page 131  time 0:03:26.665464
page 132  time 0:03:28.289967
page 133  time 0:03:29.930739
page 134  time 0:03:31.426074
page 135  time 0:03:33.027756
page 136  time 0:03:34.504160
page 137  time 0:03:36.117021
page 138  time 0:03:37.721274
page 139  time 0:03:39.386193
page 140  time 0:03:40.922506
page 141  time 0:03:42.604810
page 142  time 0:03:44.175620
page 143  time 0:03:45.827827
page 144  time 0:03:47.424135
page 145  time 0:03:49.159170
page 146  time 0:03:50.830786
page 147  time 0:03:52.442381
page 148  time 0:03:54.138761
page 149  time 0:03:55.809431
page 150  time 0:03:57.601031
page 151  time 0:03:59.373126
page 152  time 0:04:01.075737
page 153  time 0:04:02.675433
page 154  time 0:04:04.362029
page 155  time 0:04:05.956434
page 156  time 0:04:07.587088
page 157  time 0:04:09.177069
page 158  time 0:04:10.915273
page 159  time 0:04:12.416594
page 160  time 0:04:13.884059
page 161  time 0:04:15.418955
page 162  time 0:04:16.853917
page 163  time 0:04:18.525311
page 164  time 0:04:20.035475
page 165  time 0:04:21.672633
page 166  time 0:04:23.718525
page 167  time 0:04:25.354606
page 168  time 0:04:27.100770
page 169  time 0:04:28.676969
page 170  time 0:04:30.390819
page 171  time 0:04:32.022847
page 172  time 0:04:33.761970
page 173  time 0:04:35.497532
page 174  time 0:04:37.142541
page 175  time 0:04:38.915832
page 176  time 0:04:40.574625
page 177  time 0:04:42.261382
page 178  time 0:04:43.915991
page 179  time 0:04:45.656431
page 180  time 0:04:47.488378
page 181  time 0:04:49.283896
page 182  time 0:04:50.974380
page 183  time 0:04:52.618940
page 184  time 0:04:54.345987
page 185  time 0:04:56.127754
page 186  time 0:04:57.739665
page 187  time 0:04:59.509708
page 188  time 0:05:01.216207
page 189  time 0:05:02.964027
page 190  time 0:05:04.605186
page 191  time 0:05:06.364802
page 192  time 0:05:08.181846
page 193  time 0:05:09.852244
page 194  time 0:05:11.557709
page 195  time 0:05:13.340051
page 196  time 0:05:15.040574
page 197  time 0:05:16.770147
page 198  time 0:05:18.527960
page 199  time 0:05:20.276339
page 200  time 0:05:21.960812
page 201  time 0:05:23.639379
page 202  time 0:05:25.364283
page 203  time 0:05:27.096392
page 204  time 0:05:28.777674
page 205  time 0:05:30.420703
page 206  time 0:05:32.062709
page 207  time 0:05:33.833848
page 208  time 0:05:35.565506
page 209  time 0:05:37.193321
page 210  time 0:05:38.886525
page 211  time 0:05:40.689441
page 212  time 0:05:42.495362
page 213  time 0:05:44.230707
page 214  time 0:05:45.949674
page 215  time 0:05:47.704759
page 216  time 0:05:49.458315
page 217  time 0:05:51.134137
page 218  time 0:05:52.705022
page 219  time 0:05:54.306126
page 220  time 0:05:56.020893
page 221  time 0:05:57.754592
page 222  time 0:05:59.504937
page 223  time 0:06:01.190882
page 224  time 0:06:02.957072
page 225  time 0:06:04.621699
page 226  time 0:06:06.448768
page 227  time 0:06:08.097427
page 228  time 0:06:09.871618
page 229  time 0:06:11.588375
page 230  time 0:06:13.281261
page 231  time 0:06:14.966622
page 232  time 0:06:16.601766
page 233  time 0:06:18.347064
page 234  time 0:06:20.092022
page 235  time 0:06:21.833690
page 236  time 0:06:23.593748
page 237  time 0:06:25.216313
page 238  time 0:06:26.953557
page 239  time 0:06:28.664491
page 240  time 0:06:30.844176
page 241  time 0:06:32.578094
page 242  time 0:06:34.327525
page 243  time 0:06:36.172883
page 244  time 0:06:37.940581
page 245  time 0:06:39.776802
page 246  time 0:06:41.571947
page 247  time 0:06:43.345801
page 248  time 0:06:45.219264
page 249  time 0:06:46.926722
page 250  time 0:06:48.779116
page 251  time 0:06:50.548651
page 252  time 0:06:52.387565
page 253  time 0:06:54.203342
page 254  time 0:06:55.878654
page 255  time 0:06:57.528089
page 256  time 0:06:59.260711
page 257  time 0:07:01.067425
page 258  time 0:07:02.904951
page 259  time 0:07:04.636719
page 260  time 0:07:06.445676
page 261  time 0:07:08.235340
page 262  time 0:07:10.083431
page 263  time 0:07:11.922958
page 264  time 0:07:13.745747
page 265  time 0:07:15.563876
page 266  time 0:07:17.409242
page 267  time 0:07:19.126183
page 268  time 0:07:20.870681
page 269  time 0:07:22.684753
page 270  time 0:07:24.463308
page 271  time 0:07:26.374049
page 272  time 0:07:28.137553
page 273  time 0:07:29.955071
page 274  time 0:07:31.694762
page 275  time 0:07:33.538743
page 276  time 0:07:35.255421
page 277  time 0:07:37.024327

page 278  time 0:07:38.756269
page 279  time 0:07:40.508195
page 280  time 0:07:42.367874
page 281  time 0:07:44.201268
page 282  time 0:07:46.042094
page 283  time 0:07:47.881235
page 284  time 0:07:49.711590
page 285  time 0:07:51.463836
page 286  time 0:07:53.234292
page 287  time 0:07:55.054690
page 288  time 0:07:56.926812
page 289  time 0:07:58.699185
page 290  time 0:08:00.470042
page 291  time 0:08:02.222684
page 292  time 0:08:03.991975
page 293  time 0:08:05.819210
page 294  time 0:08:07.658474
page 295  time 0:08:09.339029
page 296  time 0:08:11.067499
page 297  time 0:08:12.790022
page 298  time 0:08:14.444941
page 299  time 0:08:16.354614
page 300  time 0:08:18.441625
page 301  time 0:08:20.356172
page 302  time 0:08:22.224336
page 303  time 0:08:24.045552
page 304  time 0:08:25.963943
page 305  time 0:08:27.935476
page 306  time 0:08:29.783944
page 307  time 0:08:31.515995
page 308  time 0:08:33.732004
page 309  time 0:08:35.503986
page 310  time 0:08:37.366651
page 311  time 0:08:39.207526
page 312  time 0:08:41.084586
page 313  time 0:08:42.986878
page 314  time 0:08:44.793332
page 315  time 0:08:46.677432
page 316  time 0:08:48.463386
page 317  time 0:08:50.259522
page 318  time 0:08:52.115202
page 319  time 0:08:53.952489
page 320  time 0:08:55.721304
page 321  time 0:08:57.541483
page 322  time 0:08:59.381901
page 323  time 0:09:01.233010
page 324  time 0:09:03.073626
page 325  time 0:09:04.938723
page 326  time 0:09:06.734922
page 327  time 0:09:08.618673
page 328  time 0:09:10.539436
page 329  time 0:09:12.545648
page 330  time 0:09:14.335690
page 331  time 0:09:16.178141
page 332  time 0:09:17.924617
page 333  time 0:09:19.746459
page 334  time 0:09:21.611536
page 335  time 0:09:23.457925
page 336  time 0:09:25.307163
page 337  time 0:09:27.279702
page 338  time 0:09:29.125279
page 339  time 0:09:31.036907
page 340  time 0:09:32.969759
page 341  time 0:09:34.863235
page 342  time 0:09:36.681762
page 343  time 0:09:38.620091
page 344  time 0:09:40.564067
page 345  time 0:09:42.363368
page 346  time 0:09:44.147601
page 347  time 0:09:46.017659
page 348  time 0:09:47.838471
page 349  time 0:09:49.935648
page 350  time 0:09:51.834250
page 351  time 0:09:53.644048
page 352  time 0:09:55.392294
page 353  time 0:09:57.213410
page 354  time 0:09:59.068999
page 355  time 0:10:00.776262
page 356  time 0:10:02.515224
page 357  time 0:10:04.368130
page 358  time 0:10:06.173868
page 359  time 0:10:08.043681
page 360  time 0:10:09.868014
page 361  time 0:10:11.747579
page 362  time 0:10:13.654621
page 363  time 0:10:15.594146
page 364  time 0:10:17.339176
page 365  time 0:10:19.225716
page 366  time 0:10:21.014125
page 367  time 0:10:22.876000
page 368  time 0:10:24.622292
page 369  time 0:10:26.596163
page 370  time 0:10:28.507129
page 371  time 0:10:30.468749
page 372  time 0:10:32.708425
page 373  time 0:10:34.599187
page 374  time 0:10:36.597168
page 375  time 0:10:38.922426
page 376  time 0:10:40.840065
page 377  time 0:10:42.752393
page 378  time 0:10:44.641859
page 379  time 0:10:46.534182
page 380  time 0:10:48.506347
page 381  time 0:10:50.469829
page 382  time 0:10:52.305518
page 383  time 0:10:54.146803
page 384  time 0:10:56.019971
page 385  time 0:10:57.954719
page 386  time 0:10:59.829210
page 387  time 0:11:01.715818
page 388  time 0:11:03.760699
page 389  time 0:11:05.784796
page 390  time 0:11:07.630411
page 391  time 0:11:09.484168
page 392  time 0:11:11.328302
page 393  time 0:11:13.269725
page 394  time 0:11:15.214550
page 395  time 0:11:17.165629
page 396  time 0:11:19.026662
page 397  time 0:11:20.989014
page 398  time 0:11:23.042011
page 399  time 0:11:25.031391
page 400  time 0:11:26.942285
page 401  time 0:11:28.921830
page 402  time 0:11:30.808667
page 403  time 0:11:32.744628
page 404  time 0:11:34.688276
page 405  time 0:11:36.780577
page 406  time 0:11:38.662863
page 407  time 0:11:40.756663
page 408  time 0:11:42.683590
page 409  time 0:11:44.556689
page 410  time 0:11:46.472093
page 411  time 0:11:48.438864
page 412  time 0:11:50.611977
page 413  time 0:11:52.487623
page 414  time 0:11:54.390234
page 415  time 0:11:56.298716
page 416  time 0:11:58.629148
page 417  time 0:12:00.666009
page 418  time 0:12:02.524570
page 419  time 0:12:04.524366
page 420  time 0:12:06.562111
page 421  time 0:12:08.530503
page 422  time 0:12:10.432772
page 423  time 0:12:12.387939
page 424  time 0:12:14.302416
page 425  time 0:12:16.271629
page 426  time 0:12:18.186010
page 427  time 0:12:20.088000
page 428  time 0:12:22.032825
page 429  time 0:12:24.100558
page 430  time 0:12:26.021937
page 431  time 0:12:27.972884
page 432  time 0:12:29.908115
page 433  time 0:12:31.888513
page 434  time 0:12:33.921656
page 435  time 0:12:35.939878
page 436  time 0:12:37.896006
page 437  time 0:12:39.867992
page 438  time 0:12:41.724392
page 439  time 0:12:43.618333
page 440  time 0:12:45.468623
page 441  time 0:12:47.439950
page 442  time 0:12:49.354237
page 443  time 0:12:51.280639
page 444  time 0:12:53.159391
page 445  time 0:12:55.128233
page 446  time 0:12:58.004461
page 447  time 0:12:59.876068
page 448  time 0:13:01.858980
page 449  time 0:13:03.841001
page 450  time 0:13:05.783523
page 451  time 0:13:07.733507
page 452  time 0:13:09.665284
page 453  time 0:13:11.647067
page 454  time 0:13:13.583844
page 455  time 0:13:15.585627
page 456  time 0:13:17.531394
page 457  time 0:13:19.449421
page 458  time 0:13:21.424471
page 459  time 0:13:23.306387
page 460  time 0:13:25.313540
page 461  time 0:13:27.496747
page 462  time 0:13:29.461425
page 463  time 0:13:31.421746
page 464  time 0:13:33.409446
page 465  time 0:13:35.406772
page 466  time 0:13:37.312021
page 467  time 0:13:39.348582
page 468  time 0:13:41.295835
page 469  time 0:13:43.275331
page 470  time 0:13:45.189986
page 471  time 0:13:47.110803
page 472  time 0:13:49.061770
page 473  time 0:13:51.043243
page 474  time 0:13:53.077082
page 475  time 0:13:55.036308
page 476  time 0:13:56.967828
page 477  time 0:13:58.911261
page 478  time 0:14:00.753828
page 479  time 0:14:02.719034
page 480  time 0:14:04.687355
page 481  time 0:14:06.730651
page 482  time 0:14:08.638455
page 483  time 0:14:10.572533
page 484  time 0:14:12.542293
page 485  time 0:14:14.616851
page 486  time 0:14:16.573347
page 487  time 0:14:18.579904
page 488  time 0:14:20.590872
page 489  time 0:14:22.581568
page 490  time 0:14:24.513157
page 491  time 0:14:26.472730
page 492  time 0:14:28.467522
page 493  time 0:14:30.450299
page 494  time 0:14:32.482429
page 495  time 0:14:34.559369
page 496  time 0:14:36.552130
page 497  time 0:14:38.561682
page 498  time 0:14:40.607224
page 499  time 0:14:42.552163
page 500  time 0:14:44.558313
page 501  time 0:14:46.556301
page 502  time 0:14:48.494416
page 503  time 0:14:50.645682
page 504  time 0:14:52.730604
page 505  time 0:14:54.729647
page 506  time 0:14:56.793611
page 507  time 0:14:58.768721
page 508  time 0:15:00.945785
page 509  time 0:15:03.039893
page 510  time 0:15:05.039314
page 511  time 0:15:06.989843
page 512  time 0:15:09.118299
page 513  time 0:15:11.135607
page 514  time 0:15:13.183386
page 515  time 0:15:15.230386
page 516  time 0:15:17.309872
page 517  time 0:15:19.334296
page 518  time 0:15:21.270689
page 519  time 0:15:23.326020
page 520  time 0:15:25.302166
page 521  time 0:15:27.320099
page 522  time 0:15:29.466059
page 523  time 0:15:31.507574
page 524  time 0:15:33.552040
page 525  time 0:15:35.512717
page 526  time 0:15:37.593487
page 527  time 0:15:39.713341
page 528  time 0:15:41.743861
page 529  time 0:15:43.987668
page 530  time 0:15:46.169903
page 531  time 0:15:48.212044
page 532  time 0:15:50.298157
page 533  time 0:15:52.342854
page 534  time 0:15:54.397846
page 535  time 0:15:56.515361
page 536  time 0:15:58.592489
page 537  time 0:16:00.574979
page 538  time 0:16:02.570780
page 539  time 0:16:04.596443
page 540  time 0:16:06.693508
page 541  time 0:16:08.700025
page 542  time 0:16:10.747943
page 543  time 0:16:12.799834
page 544  time 0:16:14.877869
page 545  time 0:16:16.896294
page 546  time 0:16:19.001604
page 547  time 0:16:21.160192
page 548  time 0:16:23.235031
page 549  time 0:16:25.300079
page 550  time 0:16:27.345355
page 551  time 0:16:29.319647

page 552  time 0:16:31.364535
page 553  time 0:16:33.388546
page 554  time 0:16:35.427714
page 555  time 0:16:37.490028
page 556  time 0:16:39.527426
page 557  time 0:16:41.448951
page 558  time 0:16:43.348522
page 559  time 0:16:45.479105
page 560  time 0:16:47.435363
page 561  time 0:16:49.878500
page 562  time 0:16:51.927632
page 563  time 0:16:53.860114
page 564  time 0:16:55.949465
page 565  time 0:16:57.974249
page 566  time 0:16:59.920335
page 567  time 0:17:01.862321
page 568  time 0:17:03.826789
page 569  time 0:17:05.781412
page 570  time 0:17:07.811109
page 571  time 0:17:09.857285
page 572  time 0:17:11.781720
page 573  time 0:17:13.685418
page 574  time 0:17:15.694126
page 575  time 0:17:17.607415
page 576  time 0:17:19.727126
page 577  time 0:17:21.738761
page 578  time 0:17:23.726144
page 579  time 0:17:25.730192
page 580  time 0:17:27.692378
page 581  time 0:17:29.674126
page 582  time 0:17:31.685736
page 583  time 0:17:33.822307
page 584  time 0:17:36.011438
page 585  time 0:17:38.129368
page 586  time 0:17:40.182810
page 587  time 0:17:42.126599
page 588  time 0:17:44.182802
page 589  time 0:17:46.161811
page 590  time 0:17:48.279536
page 591  time 0:17:50.296145
page 592  time 0:17:52.288829
page 593  time 0:17:54.428957
page 594  time 0:17:56.480020
page 595  time 0:17:58.480094
page 596  time 0:18:00.608983
page 597  time 0:18:02.728415
page 598  time 0:18:04.768272
page 599  time 0:18:06.770580
page 600  time 0:18:08.835956
page 601  time 0:18:10.926727
page 602  time 0:18:12.953221
page 603  time 0:18:15.017661
page 604  time 0:18:17.105746
page 605  time 0:18:19.232917
page 606  time 0:18:21.361196
page 607  time 0:18:23.536097
page 608  time 0:18:25.713263
page 609  time 0:18:27.778909
page 610  time 0:18:29.859759
page 611  time 0:18:31.931475
page 612  time 0:18:34.209589
page 613  time 0:18:36.357538
page 614  time 0:18:38.589285
page 615  time 0:18:39.408678
page 616  time 0:18:41.585135
page 617  time 0:18:43.607678
page 618  time 0:18:45.656280
page 619  time 0:18:47.703792
page 620  time 0:18:49.750876
page 621  time 0:18:50.468533

In [5]:
df.head()

,title,platform,psd_URL,icon_URL,price,status
0,Tom Clancy's Ghost Recon Wildlands Definitive ...,PS4,https://psdeals.net/ua-store/game/3250583/tom-...,https://store.playstation.com/store/api/chihir...,"2,999.00₴",NaN
1,The Relic: First Guardian,PS5,https://psdeals.net/ua-store/game/3249395/the-...,https://store.playstation.com/store/api/chihir...,"1,699.00₴",NaN
2,Xtreme Traffic Racing,PS5,https://psdeals.net/ua-store/game/3249394/xtre...,https://store.playstation.com/store/api/chihir...,259.00₴,NaN
3,Xtreme Traffic Racing,PS4,https://psdeals.net/ua-store/game/3249393/xtre...,https://store.playstation.com/store/api/chihir...,259.00₴,NaN
4,Seishin,PS5,https://psdeals.net/ua-store/game/3249392/seishin,https://store.playstation.com/store/api/chihir...,194.00₴,NaN

In [6]:
delete_lst = ['PS3', 'PS Vita', 'PS3 / PS Vita / PSP', 
              'PS Vita / PSP', 'PS3 / PS Vita', 'PS3 / PSP', 'PSP' ]

for del_pl in delete_lst:
    df = df[df.platform != del_pl]

In [7]:
if compare_old:
    df_res = pd.merge(df, df_previous, on=['title', 'platform', 'psd_URL'], how='outer')
    df_res['status'] = df_res[['status_x', 'status_y']].max(axis=1).fillna(0) 
    df_res['price'] = df_res['price_x'].combine_first(df_res['price_y'])
    #df_res['psd_URL'] = df_res['psd_URL_x'].combine_first(df_res['psd_URL_y'])
    df_res['icon_URL'] = df_res['icon_URL_x'].combine_first(df_res['icon_URL_y'])
    df_res.drop(['status_x', 'status_y', 
                  'price_x', 'price_y', 
                  'icon_URL_y', 'icon_URL_x'], inplace=True, axis=1)
    
    df_res = df_res[['title', 'platform', 'psd_URL', 'icon_URL', 'price', 'status']]
else:
    df_res = df
    df_res['status'] = 0
    
df_res = df_res.drop_duplicates(subset=['title', 'platform', 'psd_URL'], keep=False)
df_res = df_res.sort_values(by=['status', 'title'], ascending=[False, True]).reset_index(drop=True)

In [8]:
df_res.head(5)

,title,platform,psd_URL,icon_URL,price,status
0,"""Buy The Game, I Have a Gun"" -Sheesh-Man",PS5 / PS4,https://psdeals.net/ua-store/game/3094224/buy-...,https://store.playstation.com/store/api/chihir...,329.00₴,0
1,"""Buy The Game, I Have a Gun"" -Sheesh-Man",PS4,https://psdeals.net/ua-store/game/2538119/buy-...,https://store.playstation.com/store/api/chihir...,329.00₴,0
2,"""Buy The Game, I Have a Gun"" -Sheesh-Man : Dig...",PS5 / PS4,https://psdeals.net/ua-store/game/3094226/buy-...,https://store.playstation.com/store/api/chihir...,399.00₴,0
3,"""Buy The Game, I Have a Gun"" -Sheesh-Man : Dig...",PS4,https://psdeals.net/ua-store/game/2538120/buy-...,https://store.playstation.com/store/api/chihir...,399.00₴,0
4,#BLUD,PS4,https://psdeals.net/ua-store/game/2793941/blud,https://store.playstation.com/store/api/chihir...,819.00₴,0

In [9]:
df_res.shape

(20141, 6)

In [10]:
try:
    df_previous.shape
except Exception:
    pass

In [11]:
df_res.to_csv(filename, index=False)